apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.srv.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app: {{ .Values.services.srv.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.srv.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.srv.name }}
    spec:
      containers:
        - image: "{{ .Values.dockerID }}/{{ .Values.services.srv.image.repository }}:{{ .Values.services.srv.image.tag }}"
          name: {{ .Values.services.srv.name }}
          imagePullPolicy: {{ .Values.services.srv.image.pullPolicy }}
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - name: http
              containerPort: {{ .Values.services.srv.image.port }}
<% if(authentication || apiS4HC || hana || apiGraph || apiDest){ -%>
          volumeMounts:
<% } -%>
<% if(authentication || apiS4HC || apiGraph || apiDest){ -%>
            - name: <%= projectName %>-uaa
              mountPath: "/etc/secrets/sapcp/xsuaa/<%= projectName %>-uaa"
              readOnly: true
<% } -%>
<% if(apiS4HC || apiGraph || apiDest){ -%>
            - name: <%= projectName %>-dest
              mountPath: "/etc/secrets/sapcp/destination/<%= projectName %>-dest"
              readOnly: true
<% } -%>
<% if(hana){ -%>
            - name: <%= projectName %>-hdi
              mountPath: "/etc/secrets/sapcp/hana/<%= projectName %>-hdi"
              readOnly: true
<% } -%>
<% if(dockerRepositoryVisibility === 'private'){ -%>
      imagePullSecrets:
        - name: {{ .Values.services.srv.image.imagePullSecretName }}
<% } -%>
<% if(authentication || apiS4HC || hana || apiGraph || apiDest){ -%>
      volumes:
<% } -%>
<% if(authentication || apiS4HC || apiGraph || apiDest){ -%>
        - name: <%= projectName %>-uaa
          secret:
            secretName: {{ .Values.services.uaa.bindingSecretName }}
<% } -%>
<% if(apiS4HC || apiGraph || apiDest){ -%>
        - name: <%= projectName %>-dest
          secret:
            secretName: {{ .Values.services.dest.bindingSecretName }}
<% } -%>
<% if(hana){ -%>
        - name: <%= projectName %>-hdi
          secret:
            secretName: {{ .Values.services.hdi.bindingSecretName }}
<% } -%>