---
general:
<% if(BTPRuntime === 'Kyma'){ -%>
  buildTool: "docker"
  containerImageName: "<%= dockerID %>/<%= projectName %>-srv"
  containerImageTag: "latest"
  containerRegistryUrl: "https://index.docker.io"
service:
  automaticVersioning: false
  dockerConfigJsonSecretTextCredentialsId: "docker"
  Acceptance:
    kubeConfigSecretTextCredentialsId: "kyma"
    helmValuePath: "helm/<%= projectName %>-srv/values.yaml"
  Release:
    kubeConfigSecretTextCredentialsId: "kyma"
    helmValuePath: "helm/<%= projectName %>-srv/values.yaml"
steps:
  kanikoExecute:
    dockerfilePath: "srv/Dockerfile"
stages:
  Build:
    kanikoExecute: true
  Acceptance:
    kubernetesDeploy: false
  Release:
    kubernetesDeploy: true
    deployTool: "helm3"
    namespace: "<%= namespace %>"
    chartPath: "helm/<%= projectName %>-srv"
    deploymentName: "<%= projectName %>-srv"
    force: false
<% } else { -%>
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ11N16" #see SAP Continuous Integration and Delivery service for more build tool version options
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true
  Additional Unit Tests:
    npmExecuteScripts: false
  Acceptance:
    cloudFoundryDeploy: false
    cfApiEndpoint: "<%= cfapi %>"
    cfOrg: "<%= cforg %>"
    cfSpace: "<%= cfspace %>"
    cfAppName: "<%= projectName %>"
    cfCredentialsId: "deploy-to-cf"
    deployType: "standard"
    npmExecuteEndToEndTests: false
  Compliance:
    sonarExecuteScan: false
  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "<%= cfapi %>"
    cfOrg: "<%= cforg %>"
    cfSpace: "<%= cfspace %>"
    cfAppName: "<%= projectName %>"
    cfCredentialsId: "deploy-to-cf"
    deployType: "standard"
    tmsUpload: false
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  npmExecuteLint:
    failOnError: true
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "qa"
    credentialsId: "tms-sk"
<% } -%>