dockerID: <%= dockerID %>
clusterDomain: <%= clusterDomain %>
gateway: <%= gateway %>
services:
  app:
    name: <%= projectName %>-app
  srv:
    name: <%= projectName %>-srv
    image:
<% if(dockerRepositoryName !== ''){ -%>
      repository: <%= dockerRepositoryName %>
      tag: "<%= projectName %>-srv"
<% } else { -%>
      repository: <%= projectName %>-srv
      tag: "latest"
<% } -%>
      pullPolicy: Always
<% if(dockerRepositoryVisibility === 'private'){ -%>
      imagePullSecretName: <%= dockerRegistrySecretName %>
<% } -%>
      port: 5001
    service:
      port: 5001
<% if(authentication || apiS4HC || apiGraph || apiDest){ -%>
  uaa:
    name: <%= projectName %>-uaa
    xsappname: <%= projectName %>
    bindingName: <%= projectName %>-uaa-binding
    bindingSecretName: <%= projectName %>-uaa-binding-secret
<% } -%>
<% if(apiS4HC || apiGraph || apiDest){ -%>
  dest:
    name: <%= projectName %>-dest
    bindingName: <%= projectName %>-dest-binding
    bindingSecretName: <%= projectName %>-dest-binding-secret
<% if(apiS4HC || apiGraph || apiSACTenant){ -%>
    ApplicationInterfaceKey: <SetValue>
<% if(apiS4HC){ -%>
    APIKey: <SetValue>
<% } -%>
<% if(apiGraph){ -%>
    graph:
      clientId: <SetValue>
      clientSecret: <SetValue>
<% if(!apiGraphSameSubaccount){ -%>
      alias: <SetValue>
<% } -%>
<% } -%>
<% if(apiSACTenant){ -%>
    SAC:
      clientId: <SetValue>
      clientSecret: <SetValue>
<% } -%>
<% } -%>
<% } -%>
<% if(hana){ -%>
  hdi:
    name: <%= projectName %>-hdi
    bindingName: <%= projectName %>-hdi-binding
    bindingSecretName: <%= projectName %>-hdi-binding-secret
<% } -%>