apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.services.app.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app: {{ .Values.services.app.name }}
spec:
  host: {{ .Values.services.app.name }}
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: JSESSIONID
          path: /
          ttl: 0s