apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.redis.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/name: '{{ .Values.services.redis.name }}'
spec:
  ports:
    - name: http
      port: {{ .Values.services.redis.service.port }}
      targetPort: {{ .Values.services.redis.service.port }}
  selector:
    app: {{ .Values.services.redis.name }}