dockerID: <%= dockerID %>
jobs:
  db:
    name: <%= projectName %>-db
    image:
<% if(dockerRepositoryName !== ''){ -%>
      repository: <%= dockerRepositoryName %>
      tag: "<%= projectName %>-db"
<% } else { -%>
      repository: <%= projectName %>-db
      tag: "latest"
<% } -%>
      pullPolicy: Always
<% if(dockerRepositoryVisibility === 'private'){ -%>
      imagePullSecretName: <%= dockerRegistrySecretName %>
<% } -%>
  hdi:
    bindingSecretName: <%= projectName %>-hdi-binding-secret