dockerID: <%= dockerID %>
jobs:
  db:
    name: <%= projectName %>-db
    image:
      repository: <%= projectName %>-db
      tag: "latest"
      pullPolicy: Always
      imagePullSecretName: docker-config
  hdi:
    bindingSecretName: <%= projectName %>-hdi-binding-secret